version: 2

models:
    - name: Json_normalization_1
      description: model with the data of GA4 customer
      columns:
      - name: date
        description: unknown
      - name: sessions
        description: unknown
      - name: program_variant
        description: unknown
      - name: pageTitle
        description: unknown
      - name: program_name
        description: unknown
      - name: eventName
        description: unknown
      - name: video_duration
        description : unknown
      - name: eventName
        description: unknown
      - name: video_duration
        description: unknown
      - name: uuid
        description: unknown
      - name: property_id
        description: unknown
      - name: user_id
        description: unknown


      
        

