
version: 2

models:
    - name: Json_normalization
      description: model with the data of GA4 customer
      columns:
      - name: date
        description: unwkonw
      - name: sessions
        description: unwkonw
      - name: uuid
        description: unwkonw
      - name: User_id
        description: unwkonw
      
       
        
        

