version: 2

models:
    - name: basic_metrics_daily
      description: model with the data of GA4 customer
      columns:
      - name: date
        description: unknown
      - name: streamName
        description: unknown
      - name: sessions
        description: unknown
      - name: totalUsers
        description: unknown
      - name: activeUsers
        description: unknown
      - name: newUsers
        description: unknown
      - name: totalReturningUsers
        description : unknown
      


      
        

